site_name: Prometheus Project Docs
site_url: https://github.com/BrunoComitre/Prometheus
site_description: Project documentation with Markdown
site_author: Bruno Alves Comitre

repo_url: https://github.com/BrunoComitre/Prometheus
repo_name: BrunoComitre/Prometheus
edit_uri: tree/main/docs


theme:
  name: material
  locale: en
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  highlightjs: true
  hljs_languages:
    - yaml
    - python

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Developer Guide: dev-guide.md
  - Contributing: contributing.md
  - License: license.md
